version: 2.1
jobs:
  build:
    machine:
     image: ubuntu-2004:202107-01
    steps:
      - checkout
      # Whatever you want to do mkdir ~/bin && 
      - run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt install python python3 -y
      - run: PATH=~/bin:$PATH && sudo curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && sudo chmod a+x ~/bin/repo
      - run: df -h
      - run: git config --global user.name Your Name && git config --global user.email you@example.com
      - run: ~/bin/repo init --depth=1 -u git://github.com/DotOS/manifest.git -b dot11
      - run: ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
      - run: sudo apt install -y ccache 
      - run: sudo /usr/sbin/update-ccache-symlinks
      - run: echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
      - run: source ~/.bashrc && echo $PATH
      - run: cd project
      - run: source build/envsetup.sh
      - run: git clone https://github.com/Orangeskai/android_device_realme_RMX2001 -b DotOs --depth=1 device/realme/RMX2001
      - run: git clone https://github.com/Orangeskai/android_kernel_realme_RMX2001 -b DotOs --depth=1 kernel/realme/RMX2001
      - run: git clone https://github.com/Orangeskai/proprietary_vendor_realme -b DotOs --depth=1 vendor/realme
      - run: free